# Generated by Django 2.2.13 on 2020-07-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOADON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayThanhToan', models.DateTimeField()),
                ('SoDem', models.IntegerField()),
                ('TongTien', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LOAIKHACHHANG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiKhachHang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LOAIPHONG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiPhong', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='THONGKEDOANHTHU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoanhThu', models.IntegerField()),
                ('Thang', models.DateTimeField()),
                ('IDHoaDon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HOADON')),
                ('IDLoaiPhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LOAIPHONG')),
            ],
        ),
        migrations.CreateModel(
            name='PHONG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenPhong', models.CharField(max_length=100)),
                ('NgayThue', models.DateTimeField()),
                ('NgayTra', models.DateTimeField()),
                ('DonGia', models.IntegerField()),
                ('TinhTrang', models.CharField(max_length=100)),
                ('IDloaiphong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LOAIPHONG')),
            ],
        ),
        migrations.CreateModel(
            name='KHACHHANG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenKhachHang', models.CharField(max_length=100)),
                ('CMND', models.CharField(max_length=100)),
                ('SDT', models.IntegerField()),
                ('DiaChi', models.CharField(max_length=100)),
                ('IDLoaiKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LOAIKHACHHANG')),
                ('IDphong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PHONG')),
            ],
        ),
        migrations.AddField(
            model_name='hoadon',
            name='IDKhachHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.KHACHHANG'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='IDphong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PHONG'),
        ),
    ]
